# Generated by Django 4.2.1 on 2024-02-07 09:56

import accounts.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_lecturer', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_dep_head', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=60, null=True)),
                ('nationality', models.CharField(blank=True, max_length=60, null=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('picture', models.ImageField(default='default.png', null=True, upload_to='profile_pictures/%y/%m/%d/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('state_of_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('meal_allergic_comment', models.TextField(blank=True, null=True)),
                ('medical_record', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('computer_labs', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('library_services', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('counseling', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('student_housing', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('financial_aid', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('cafeteria_services', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('mental_health_services', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('tutoring_centers', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('technology_support', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('disability_services', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('international_student_services', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('laboratory_facilities', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('academic_advising', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('bus_service', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_now', 'Not Now')], default='not_now', max_length=10)),
                ('bus_service_type', models.CharField(blank=True, choices=[('both-ways', 'Both Ways'), ('one-way', 'One-way'), ('not_now', 'Not Now')], default='not_now', max_length=10, null=True)),
                ('pickup_or_dropoff', models.CharField(blank=True, choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('not_now', 'Not Now')], default='not_now', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, choices=[('', '--'), ('Creech', 'Creech'), ('Nusery', 'Nusery Certificate'), ('Basic', 'Basic Certificate')], default='', max_length=25, null=True)),
                ('year', models.CharField(blank=True, choices=[('', '--'), ('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX')], default='', max_length=25, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=60, null=True)),
                ('alt_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('relation_ship', models.CharField(blank=True, max_length=60, null=True)),
                ('email_p', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_id', models.CharField(blank=True, default='', max_length=20)),
                ('level', models.CharField(choices=[('', '--'), ('Creech', 'Creech'), ('Nusery', 'Nusery Certificate'), ('Basic', 'Basic Certificate')], default='', max_length=25)),
                ('term', models.CharField(choices=[('', '--'), ('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], default='', max_length=25)),
                ('session', models.CharField(choices=[('', '--'), ('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX')], default='', max_length=25)),
                ('payment', models.CharField(blank=True, choices=[('', '--'), ('PENDING  ❌', 'Pending'), ('APPROVED ✔', 'Approved'), ('ADVANCED 🕛', 'Advanced')], default='', max_length=25, null=True)),
            ],
        ),
    ]
